### ISSUE TITLE
点赞的接口

### ISSUE THREAD

**Issue by indooorsman** [czp3009/bilibili-api#12]
求作者分析下点赞的接口

**Comment by czp3009** [comment]
对评论的点赞

示例

POST https://api.bilibili.com/x/v2/reply/action HTTP/1.1

access_key: 2848494192f8ab0ffe3c09d5bd367f21
action:     1
appkey:     1d8b6e7d45233436
build:      5370000
channel:    html5_app_bili
mobi_app:   android
oid:        43670232
platform:   android
rpid:       1390727249
ts:         1550743298
type:       1
sign:       9218c66bfeebb92c99f61e274842cac9

URLEncoded Form

action 为 1 时是点赞, 0 为取消点赞

oid 即 aid, av 号, 视频的唯一标识.

rpid 是 replyId, 评论的唯一标识.


对视频的点赞

示例

POST https://app.bilibili.com/x/v2/view/like HTTP/1.1

access_key: 2848494192f8ab0ffe3c09d5bd367f21
aid:        43670232
appkey:     1d8b6e7d45233436
build:      5370000
channel:    html5_app_bili
dislike:    0
from:       7
like:       0
mobi_app:   android
platform:   android
ts:         1550743574
sign:       595a8277416e14133ebcfa270d763665

URLEncoded Form

aid 同上

这个接口的两个参数 like 和 dislike, dislike 永远为 0.

like 如果为 0, 表示点赞, 为 1 表示取消点赞.

另一个接口是 POST https://app.bilibili.com/x/v2/view/dislike HTTP/1.1

参数一模一样.

在这个接口中, like 永远为 0, dislike 为 0 表示不喜欢, 为 1 表示取消不喜欢.

可以在不喜欢的同时取消点赞(dislike 接口), 此时 like 为 1, dislike 为 0.

签名算法见隔壁 https://github.com/czp3009/bilibili-api/issues/10
