### ISSUE TITLE
添加依赖后出错。。

### ISSUE THREAD

**Issue by a747368836** [czp3009/bilibili-api#15]
添加后出现了这个。。。请教下大佬还有其他方式使用B站api吗。。andorid新人想练练手 android.support.multidex.MultiDexApplication: java.lang.ClassNotFoundException

**Comment by czp3009** [comment]
由于库本身以及依赖加起来比较大，所以会导致单 dex 文件放不下这么多内容。为了规避此问题，必须要开启 Android 的 MultiDex 支持，详见
https://developer.android.com/studio/build/multidex

目前，这个库甚至还没有开发包括 查看普通视频，查看评论，查看番剧视频 等 功能。如果要练练手的话，大概要自己开发了。
