### ISSUE TITLE
请求提供说明文档

### ISSUE THREAD

**Issue by c90c90** [czp3009/bilibili-api#16]
github上还在更新的基本上只有大佬的这个项目了，B站官网也没有API文档了，请求大佬做个说明文档，谢谢！

**Comment by czp3009** [comment]
B站API太多了。

这个项目到现在也才做了直播站的API。

如果你懂一些Java的话，可以看诸如 https://github.com/czp3009/bilibili-api/blob/master/src/main/java/com/hiczp/bilibili/api/live/LiveService.java 这样的Service 类的代码。

**Comment by c90c90** [comment]
请问节奏风暴那个接口是怎么调用的，{room_id}这个地方有点看不懂，能否给个示例地址，比如我要看房间526是否有节奏风暴，还有请问如何查看辣条，亿元，节奏风暴，小金人，小电视，上舰等礼物是谁送的

**Comment by chenyitian2004** [comment]
还有请问人气值怎么获取。。

**Comment by czp3009** [comment]
如下图所示

![image](https://user-images.githubusercontent.com/17246126/45341397-25173080-b5cd-11e8-9500-19d206e29864.png)

这样就可以查看该房间有没有节奏风暴.

由于不明确存在节奏风暴的房间的 data 字段的内容是什么, 所以暂时设定类型为 JsonElement, 预期应该与小电视的差不多, 详见模型

https://github.com/czp3009/bilibili-api/blob/master/src/main/java/com/hiczp/bilibili/api/live/entity/AppSmallTVEntity.java

礼物是谁送的是没有记录的, 正常情况下访问一个直播间时, 在进入房间的时间点之前被送出的礼物, 客户端都是不知道的.

看直播时, 会有一个 socket 连接到弹幕退送服务器, 同时也在这一 socket 中推送礼物和广播. 这个 socket 中会传输送礼物的详细消息, 模型详见

https://github.com/czp3009/bilibili-api/blob/master/src/main/java/com/hiczp/bilibili/api/live/socket/entity/SendGiftEntity.java

截包记录详见

https://github.com/czp3009/bilibili-api/blob/master/record/bullet_screen_stream_json/SEND_GIFT.json

socket 连接示例详见

https://github.com/czp3009/bilibili-api#socket
