### ISSUE TITLE
您好，我这里在你的model里加了根据roomId去“打开直播”和“关闭直播”，能否提到你的分支上？

### ISSUE THREAD

**Issue by MRDHR** [czp3009/bilibili-api#17]
具体代码如下
` /**
     * 获取直播分区列表，多层
     *
     * @return 成功时code为0
     */
    @GET("room/v1/Area/getList?show_pinyin=1")
    Call<LiveAreaListEntity> getLiveAreaList();

    /**
     * 获取直播间信息（主要是拿roomId）
     *
     * @return LiveInfoEntity
     */
    @GET("i/api/liveinfo")
    Call<LiveInfoEntity> getLiveInfo();

    /**
     * 根据roomId 获取推流的地址
     *
     * @param roomId
     * @return LiveRoomStreamInfoEntity
     */
    @GET("live_stream/v1/StreamList/get_stream_by_roomId")
    Call<LiveRoomStreamInfoEntity> getStreamByRoomId(@Query("room_id") String roomId);

    /**
     * 开始直播
     *
     * @param roomId
     * @param platform 固定PC
     * @param areaId 子分区id 譬如学习的id为27
     * @param csrfToken (csrfToken是cookie里的bili_jct cookie这个的值)
     * @return StartLiveEntity
     */
    @POST("room/v1/Room/startLive")
    Call<StartLiveEntity> startLive(@Query("room_id") String roomId, @Query("platform") String platform,
                                    @Query("area_v2") String areaId, @Query("csrf_token") String csrfToken);

    /**
     * 停止直播
     *
     * @param roomId
     * @param platform
     * @param areaId
     * @param csrfToken
     * @return
     */
    @POST("room/v1/Room/stopLive")
    Call<StopLiveEntity> stopLive(@Query("room_id") String roomId, @Query("platform") String platform,
                                  @Query("area_v2") String areaId, @Query("csrf_token") String csrfToken);`

**Comment by czp3009** [comment]
这个不是移动端API吧。

现在Web端的API有很多参数在HTML中内联的 script 里面，导致一些Web端API已经做不了了。

所以Web端API已经不想维护了。

**Comment by MRDHR** [comment]
是的，这个是用网页那边的api做的。你这边不需要的话，我就不申请合并了。主要是自己做了个转播流的工具用了下，谢谢你提供的model。

**Comment by czp3009** [comment]
好的
