### ISSUE TITLE
这个库有没有安卓版本限制呢？

### ISSUE THREAD

**Issue by luern0313** [czp3009/bilibili-api#18]

**Comment by czp3009** [comment]
没有测试过，不过应该没有

**Comment by luern0313** [comment]
在安卓5.1上显示找不到Instant的class，但是安卓p上没有这个问题

**Comment by czp3009** [comment]
instant是Android自带类，找不到Instant我不明确是什么意思。

如果看到了ClassNotFound，可能是dex文件切分问题，见此 https://github.com/czp3009/bilibili-api/issues/15

**Comment by luern0313** [comment]
这是添加了这个之后才出现的问题。。。

**Comment by czp3009** [comment]
那你发一下是什么报错

**Comment by luern0313** [comment]
![image](https://user-images.githubusercontent.com/25398864/46569021-7f63a100-c981-11e8-8774-471336ab79db.png)
是这个

**Comment by luern0313** [comment]
算了算了，这么问你也不太好，我另想办法吧，谢谢了

**Comment by czp3009** [comment]
这个Instant是Java8的时间操作类，Android上需要用Jack(好像现在不是用Jack了)来转换到Java7，具体的Google一下，有关Android Java8问题

**Comment by luern0313** [comment]
好的，谢谢了
