### ISSUE TITLE
请求提供获取视频信息API

### ISSUE THREAD

**Issue by kevinlovely** [czp3009/bilibili-api#20]
传参avid 返回查询视频详情信息 感谢!

**Comment by czp3009** [comment]
如果你需要的是接口分析, 那我在这里告诉你

示例

https://app.bilibili.com/x/v2/view?ad_extra=D804FD0051D642264E5542E8CB228E41A378FECF9DDF4AD7B378C56B1D2CE1C78EDDA708D5C4420620688F7F73E9D3C1390AE0207C69C017DC9674B851586590736CA994FDDE83E3C3D9C219992C62246D2417FC7E8B5DCABF861325E05F2408CC9448D5751CE0BD5A3FF857DF145C218EE6898A5C7515150A50D3C54D1E10EEB5ED748F597AC35354B30C12DB52CF3E3EB991D49ADE750DF7591291619729F8F72B00F451E5962EA1C5E9D2B39D027613F6E8F95357711C191ADD53B18791B38A4D2B8ED75464542D9EFC9E1244FEF03092D03975B9C61D765C06F24DD9E87EB6D2066A3B11F2DBDF1A2EBC408073A3C110EFBE166543FEF2777EF679FA8B722937B575643F7E3663D85C29490E4C2C35DFAECFB24766F975B9827BF19E3A815FC333BB244FCC067E56A47F5DDD13E2D8FE45FB08AC6AEBD1BEECDC4181FEFE890A7BB5F510274EC27986273F6506C28C0B438F7547DFB6C8A9C553BF4E32ABF3AE5998D42A2ED8C8E99EB1D3F478AB4272B4935D88C7975A723EA6627C82D9ECF6B1A7EC89DCE0B424C0D78CE08614B87215D6D2F2F6CC39AE20ED54ACDA57157F74CC38EA2D555797FCEA9F2815429E5B9ED70EC4BEC5B1E90219278668326135459E78E2BE5BB34EA4CEF2393E2B81E3A965BB7F894D4A0E2F9FC8450DA2943BD04DFF120EF6835B4F187E8BECCBA3EE438A6ED965BEEDB8D0E2C82703D4BE9E6C35EA72C055DEE648AB029A39406336C031D97AA7548820761B2C1DA17082AD23F86F51A251667D653A95F5B0A8BD6C34A3D08355946741F61FFCC7ECE578530C9FE9D89AA32ADD42D36742826A9B993FB019E557C8DA9BB11E4EC82C0B11A3255A2A5E3616B4125C4693365235&aid=42463605&appkey=1d8b6e7d45233436&autoplay=0&build=5370000&channel=html5_app_bili&fnval=16&fnver=0&force_host=0&from=7&mobi_app=android&plat=0&platform=android&qn=32&trackid=all_15.shylf-ai-recsys-235.1550742259901.511&ts=1550742265&sign=0c02ccfdb7bd0477eef4816aba8e26c8

其中 aid 就是 av 号.

签名算法我在隔壁说过了 https://github.com/czp3009/bilibili-api/issues/10

如果你需要的是程序代码, 那么现在还没有, 本项目持续重构中.

**Comment by kevinlovely** [comment]
真的很感谢！！！帮助太大了！！！

czp <notifications@github.com> 于2019年2月21日周四 下午5:55写道：

**Comment by czp3009** [comment]
固定参数的含义详见 https://www.hiczp.com/2017/10/23/%E7%BD%91%E7%BB%9C/%E6%A8%A1%E6%8B%9FBilibili-Android%E5%AE%A2%E6%88%B7%E7%AB%AF%E7%99%BB%E5%BD%95/
