### ISSUE TITLE
获取到视频后怎么播放呢

### ISSUE THREAD

**Issue by lly835** [czp3009/bilibili-api#23]
http://upos-hz-mirrorkodou.acgvideo.com/upgcxcode/18/58/77995818/77995818-1-30216.m4s?e=ig8euxZM2rNcN

.m4s格式，搜了一圈，没找到安卓播放器可以播放

**Comment by czp3009** [comment]
m4s 就是 mp4

lly835 <notifications@github.com> 于 2019年8月16日周五 下午9:34写道：

**Comment by lly835** [comment]
@czp3009  不一样吧，我用ijkplayer可以播本地的m4s，但是远程的m4s播不了

**Comment by czp3009** [comment]
你把视频下载下来在自己的电脑上播放一下, 不要问, 问就我已经试过了.

lly835 <notifications@github.com> 于2019年8月19日周一 上午11:02写道：
