### ISSUE TITLE
登录失败或验证码错误时无法获取错误信息

### ISSUE THREAD

**Issue by NekoSunflower** [czp3009/bilibili-api#25]
需要输入验证码时，data中包含验证码url，但返回内容因为code非0被FailureResponseInterceptor拦截抛出BilibiliApiException无法从异常中获取data内容（只有message）

**Comment by czp3009** [comment]
B站改变了需要验证码时返回的 code 值, 有空再改

**Comment by NekoSunflower** [comment]
有计划什么时候发个包么？因为之前用的v2接口从昨天开始被B站关闭了，所以不得不转用v3接口，急需

**Comment by czp3009** [comment]
刚才在 windows 写 c#, 正在为 windows 安装 java

**Comment by czp3009** [comment]
已发布, 中央仓库的同步需数小时

向日癸 <notifications@github.com> 于 2020年1月24日周五 下午2:27写道：
