### ISSUE TITLE
个人信息接口中的硬币数可能为小数

### ISSUE THREAD

**Issue by HuanCheng65** [czp3009/bilibili-api#27]
在myInfo当中
>com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 419.3 at line 1 column 117 path $.data.coins

**Comment by pboymt** [comment]
这个的确蛋疼，因为打赏给up主的硬币只有10%的转化率。很多人不在意硬币数量很可能不知道

**Comment by czp3009** [comment]
fixed

https://github.com/czp3009/bilibili-api/commit/a728d7b4acb32461dc5c973e5d020430d912316a
