### ISSUE TITLE
提交一点api 2333

### ISSUE THREAD

**Issue by SakuraKoi** [czp3009/bilibili-api#3]
> GET https://api.live.bilibili.com/appUser/myTitleList
> access_key = 用户accessToken

获取用户拥有的所有头衔
返回

```
@SerializedName("code")
public int code;
@SerializedName("message")
public String message;
@SerializedName("data")
public MyTitlesEntity data;

public static class MyTitlesEntity {
	@SerializedName("list")
	public List<TitleEntity> list;

	public static class TitleEntity {
		@SerializedName("uid")
		public int uid;
		@SerializedName("had")
		public boolean hasTitle;
		@SerializedName("title")
		public String titleID;
		@SerializedName("status")
		public int status;
		@SerializedName("activity")
		public String activity;
		@SerializedName("score")
		public int scoreLevelup;
		@SerializedName("title_pic")
		public TitlePicEntity pic;

		public static class TitlePicEntity {
			@SerializedName("id")
			public String id;
			@SerializedName("img")
			public String imageUrl;
			@SerializedName("width")
			public int width;
			@SerializedName("height")
			public int height;
		}
	}
}
```

> POST https://api.live.bilibili.com/AppExchange/silver2coin
> access_key = 用户accessToken

银瓜子换硬币
返回code=403则当日已经换过(每天可换一个硬币)
返回数据仅ts. code和message

> GET https://api.live.bilibili.com/AppUser/wearTitle
> title = 头衔id
> access_key = 用户accessToken

佩戴头衔
头衔id为获取用户所有头衔返回的data - list - title
头衔不存在返回code=-400
返回数据仅ts. code和message

(自动带可升级头衔签到,签完换回来美滋滋2333)

**Comment by czp3009** [comment]
非常抱歉现在才回复, 由于过年琐事缠身.

"直播中心" 页面的 API 已经在计划里了, 年后大概会开工.

说 "大概" 是因为我还得重构我的弹幕姬.

非常感谢提交 issue.

**Comment by czp3009** [comment]
我有一些问题想请教一下.

请问你是用什么方式来截包的, 我发现 B站 客户端(Android)升级到最新版本之后, 把所有 API 都换成了 https 的, 导致无法得到请求内容. 客户端反编译之后的代码, 很多都混淆过了, 而且他的代码里视图代码和后台代码混在一起, 很难阅读(我之前只看了它用什么框架以及基本架构).

还有一个事情是关于 POST https://api.live.bilibili.com/AppExchange/silver2coin 这个 API.

(参数仅 access_key, appkey, sign, Query 参数)

使用 POST 方式时, 返回
```
{
	"code": 65530,
	"msg": "invalid request",
	"message": "invalid request",
	"data": "bad token"
}
```

使用 GET 方式时, 返回
```
{
	"code": 500,
	"msg": "调用wallet.exchange失败",
	"message": "调用wallet.exchange失败",
	"data": []
}
```

在客户端上完成一次兑换之后, POST 方式的请求返回值不变, GET 方式的变为
```
{
	"code": 403,
	"msg": "每天最多能兑换 1 个",
	"message": "每天最多能兑换 1 个",
	"data": []
}
```

所以这个让人摸不到头脑. 于是我试图自己截包看一下, 发现已经换成 https 了, 于是有了第一个问题.

**Comment by a632079** [comment]
有关截包的问题， 建议使用 fiddler @czp3009
安装一个针对Android/IOS ssl 的插件，之后就能通过代理，来截取 Android的 https 包了。
涉及 TCP 包的话，建议使用 wireshark

**Comment by Ldcr993519867** [comment]
截包我用的是[whistle](https://github.com/avwo/whistle)
手机上安装证书,在wlan里设置全局代理
然后[开启https截取](https://avwo.github.io/whistle/webui/https.html)

POST https://api.live.bilibili.com/AppExchange/silver2coin这个api似乎b站修改了,刚刚测试的确返回了65530 invalid request

**Comment by a632079** [comment]
💩 话说，有尝试翻译成 nodejs， 很奇怪一直登入不上。 气哭

**Comment by a632079** [comment]
是否和 UA 有关呢？

**Comment by Ldcr993519867** [comment]
这是我最新截出的请求,兑换成功

POST /AppExchange/silver2coin?access_key=<AccessToken已删除>&actionKey=appkey&appkey=1d8b6e7d45233436&build=5210000&device=android&mobi_app=android&platform=android&ts=1519125003&sign=bdfa5871267dd698b40b4b4ce2b921ba HTTP/1.1
Display-ID: 3874987-1519124057
Buvid: B6D6102C-7A7F-485F-9B37-50DA191AC2BD19984infoc
User-Agent: Mozilla/5.0 BiliDroid/5.21.0 (bbcallen@gmail.com)
Device-ID: JhZ0QnpMLUx4TihNMU0xATIDNgFlAzADMFZnXjgKaA
Content-Length: 0
Host: api.live.bilibili.com
Connection: Keep-Alive
Accept-Encoding: gzip
Cookie: sid=loasvgak
X-Kamigakusi-ID: 
x-forwarded-for: 192.168.3.15

这是Responce

HTTP/1.1 200 OK
Date: Tue, 20 Feb 2018 11:10:03 GMT
Content-Type: application/json
Content-Length: 151
Connection: keep-alive
L: v
Server: swoole-http-server
X-TKID: 1519125003558282161871
Expires: Tue, 20 Feb 2018 11:10:02 GMT
Cache-Control: no-cache
X-Cache: BYPASS from cn-jlcc-cu-w-01.hdslb.com

{"code":0,"msg":"兑换成功","message":"兑换成功","data":{"silver":"267050","gold":"1000","tid":"ae4472de4753a160736f3374084489f32122","coin":1}}

**Comment by czp3009** [comment]
@a632079 Android客户端的登录和 Web 不一样，不需要验证(指滑动验证)，但是hash code有时间限制，估计有效时间只有五秒。也就是说，五秒钟前用这个hash加密了密码之后，五秒之后这个密码密文就是无效的，所以手动测试会测不出来(cannot decrypt rsa password)。

有关 sign 算法以及登录的问题我之前写过一篇博文 https://www.hiczp.com/post-145.html 

客户端提交的内容可以分为几个类别：UA以及其他固定请求头，固定参数，API参数，sign

API参数是指这个API所需的参数，固定参数是 platform，device 等。

目前已知的所有API(service本身，不考虑日志)，都不会读取请求头，所以跟UA是没有关系的。

少量API会要求一个或多个固定参数里的参数(比如 platform)

passport有关的API全部不会读取固定参数(博文上有图表达了登录有关的参数)

**Comment by a632079** [comment]
@czp3009 十分感谢，已经成功了。
![default](https://user-images.githubusercontent.com/16975812/36487974-3601c20c-175d-11e8-820b-8487467700f8.png)
之前失败的原因 （`400`）:
  * 错误的编码方式 ， nodejs 默认是: `RSA_PKCS1_OAEP_PADDING`
![default](https://user-images.githubusercontent.com/16975812/36488106-9b63df0e-175d-11e8-95cf-ea32a8b0ec74.png)

----------------
话说大佬，我能转发一下文章。再来加个友联嘛？ 2333
https://i.a632079.me

**Comment by czp3009** [comment]
@a632079 欢迎转发。

友链加好了。

博客太丑了，一直在计划自己写一个，但是总是一个事情还没完就开新坑于是到现在还是这个样子，见笑了。

**Comment by a632079** [comment]
❤️ 子项目 https://github.com/a632079/bilibili-api 暂时只写了个登入， 友链稍晚添加。感谢帮助

**Comment by czp3009** [comment]
@Ldcr993519867 最近稍微空了一些, 安装了 whistle 试了一下.

Ubuntu 16.04 | Node v6.11.5 | Android 8.0.0 | Bilibili APP 5.22.1

(以下只讲 https)

对于在浏览器上打开普通网页, 它工作的很好, 对于普通的 APP, 例如 高德地图, 钉钉, 它也工作的很好.

对于一些安全级别较高的软件, 例如 Google Play, Gmail, APP 将提示 未连接到互联网, 推测是应用内置了 SSL 证书或者 APP 会校验整个证书链(Google Play 刷新页面时, whistle 抓到 0 个包, 刷新操作立即返回并提示 未连接到互联网).

然而, 这个 B站 客户端, 居然也是一样的情况, 所有操作都会立即返回并提示 电波无法到达, 并且 whistle 也是抓到 0 个包.

通过重启手机排除了手机自身或者 APP 自身的 SSL 缓存的问题.

通过先不安装 whistle 的证书访问自己的博客, 安装后立即再访问一次, 排除了路由器缓存 SSL 的可能性.

确认 B站 客户端不是因为 SSL 缓存而导致这个情况发生的. 可能 B站 客户端内置了证书链.

我不清楚是只有我是这样的还是确实是这样的.

**Comment by Ldcr993519867** [comment]
Ubuntu 16.04 | Node v6.12.3 | Android 6.0 | Bilibili APP 5.21.0 
HTTPS截取工作正常,你可以尝试降级一下b站app

**Comment by Ldcr993519867** [comment]
已升级至Bilibili 5.22.1 https截取正常,应当是你那的问题

**Comment by czp3009** [comment]
我升级 node 到了 v9.6.1, 升级 APP 到了 5.23.0.

依然是这个问题.

其中, webview 部分会提示(由 Android System WebView 输出的错误页面) 证书不被设备信任.

但是输出的链接(https)用外部浏览器(系统自带浏览器与 chrome)是可以打开的(https).

这个问题太鸡巴了, 我尝试换个手机再试试.

**Comment by czp3009** [comment]
@Ldcr993519867 
我尝试用 Android Studio 默认的 Android Simulator(qemu)(Android 8.0) 安装 Bilibili(5.23.0) 之后进行截包, 情况依然是浏览器可以正常访问 https 网站, 但是 Bilibili APP 提示 "电波无法到达呦".

所以我想问一下是不是我的截包姿势错了.

我是首先在 PC 上开启 whistle, 
```
w2 start
```

然后在手机上访问对应的 whistle 的网页, 安装证书, 然后开启 whistle 的 https 拦截.

之后在手机上的 wifi 设置中, 设置代理, 就像这样
![image](https://user-images.githubusercontent.com/17246126/37009415-ce9e4382-2121-11e8-84d5-1eade83ac3fa.png)

之后就出现了, chrome 可以正常访问 https 页面, 但是 B站 APP 硬是 "电波无法到达呦".

**Comment by czp3009** [comment]
我手机用的MIUI(Android8.0)，模拟器里的是原生Android8.0。

安装证书之后都不会在通知栏有提示。都可以正常访问 https 网站(chrome)并且在 whistle 看到 https 通信，response 是正确的，确实截到了 https 的内容。

包括其他 app，也都正常的(在我的手机和模拟器)，唯独 bilibili 不正常。

bilibili 在我的手机和模拟器，都会提示 "电波无法到达呦"。

-.-

**Comment by czp3009** [comment]
@Ldcr993519867  我在我的手机上截了一些图, 事情大概是这样的

首先安装证书
![image](https://user-images.githubusercontent.com/17246126/37017147-66d9de54-214a-11e8-936f-9e79cad48458.png)

然后通知栏里什么都没有(从来都没有, 重启也不会有)
![image](https://user-images.githubusercontent.com/17246126/37017157-71ddbbe0-214a-11e8-9ef2-bbdd2c520a95.png)

在浏览器访问 https 页面, 是可以打开的, 并且 whistle 截到了数据
![image](https://user-images.githubusercontent.com/17246126/37017174-84f7a326-214a-11e8-8b2c-983f39e1c060.png)

但是 Bilibili 却是这样的
![image](https://user-images.githubusercontent.com/17246126/37017188-99144346-214a-11e8-9c53-655e9a89a4be.png)

还有些页面是这样的
![image](https://user-images.githubusercontent.com/17246126/37017199-a700e284-214a-11e8-88b9-6589afb58e06.png)

另一些是这样的
![image](https://user-images.githubusercontent.com/17246126/37017204-afbd1262-214a-11e8-92ab-9de99e92c837.png)

WebView 是这样的
![image](https://user-images.githubusercontent.com/17246126/37017216-b6f9e1fe-214a-11e8-99c4-3e4e4e18b63f.png)

上面那个 WebView 抛出的错误里面的那个链接点击之后会打开系统浏览器, 是可以访问的, 并且 whistle 截到了数据
![image](https://user-images.githubusercontent.com/17246126/37017236-ce698eb6-214a-11e8-873c-d4a6fa3e7348.png)

当在 Bilibili 应用内进行刷新操作时, whistle 没有任何输出, 也就是截不到任何数据包, 然后 bilibili 的刷新操作会立即失败而不是超时.

在 Android Emulator 上情况也是一样的, 所以我已经不知道怎么办了.

**Comment by Ldcr993519867** [comment]
这真是奇了怪了.....
你的操作没有问题啊......=-=.....

**Comment by czp3009** [comment]
那黄了呀, 截不了包了.

咋回事啊, 那咋整啊, 大佬带带我啊.

=.=

我待会回去把我的小米3翻出来试一试.

**Comment by czp3009** [comment]
找了一个 ios 设备, ios 居然能正常截包 ORZ

暂时就用这个 iphone 来截包了.

(上面提到的那三个 API 之前已经做好了, 我再把取消佩戴头衔什么的补一下)

**Comment by czp3009** [comment]
粉丝勋章, 头衔, 兑换硬币的 API 都已经完成了. 将在下一个版本中发布.

**Comment by SakuraKoi** [comment]
> 那黄了呀, 截不了包了.
> 
> 咋回事啊, 那咋整啊, 大佬带带我啊.
> 
> =.=
> 
> 我待会回去把我的小米3翻出来试一试.

来自一万年后的更新
你抓包失败的原因我找到了=-=
你用的android8.0, 新版本android默认不信任用户安装的证书
要抓包得改apk添加一个xml节点开信任或者用root权限安装进系统证书库

**Comment by czp3009** [comment]
在另一个 issue 中, 我已经知道了这一点.....

SakuraKoi <notifications@github.com> 于2019年10月10日周四 上午11:54写道：
