### ISSUE TITLE
登录API无法使用，返回了错误信息

### ISSUE THREAD

**Issue by NekoSunflower** [czp3009/bilibili-api#37]
登录并进行验证码校验后返回了错误信息
{"ts":1610644416,"code":0,"data":{"status":2,"url":"https://www.bilibili.com/blackboard/activity-loginwarning.html","message":"你的帐号存在异常问题，请使用哔哩哔哩手机端APP最新版本验证后登录"}}
怀疑是否是使用的api版本过旧导致的

**Comment by duzhaokun123** [comment]
我试了一下, 默认的 appKey 会返回`验证码错误`
换一个之后就可以正常登录
所以接口没变只是 appKey 旧了

**Comment by NekoSunflower** [comment]
> 我试了一下, 默认的 appKey 会返回`验证码错误`
> 换一个之后就可以正常登录
> 所以接口没变只是 appKey 旧了

能提供一下可以使用的appKey吗？

**Comment by duzhaokun123** [comment]
@NekoSunflower 
appKey: bb3101000e232e27
appSec: 36efcfed79309338ced0380abd824ac1

**Comment by NekoSunflower** [comment]
> @NekoSunflower
> appKey: bb3101000e232e27
> appSec: 36efcfed79309338ced0380abd824ac1

换了这个之后提示 {"message":"API sign invalid","ts":1610714801,"code":-3}

**Comment by duzhaokun123** [comment]
你是不是没换 appSec

**Comment by NekoSunflower** [comment]
> 你是不是没换 appSec

我设置了 但不知道对不对 这是我设置的代码
        BilibiliClientProperties billingClientProperties = client.getBillingClientProperties();
        billingClientProperties.setAppKey("bb3101000e232e27");
        billingClientProperties.setAppSecret("36efcfed79309338ced0380abd824ac1");

> 我已经发现了appSec错误的原因 BilibiliClient在初始化时已经将appSec传递到其他对象中，后面再设置已经没用了
正确的做法应该是
        BilibiliClientProperties billingClientProperties = new BilibiliClientProperties();
        billingClientProperties.setAppKey("bb3101000e232e27");
        billingClientProperties.setAppSecret("36efcfed79309338ced0380abd824ac1");
        BilibiliClient client = new BilibiliClient(billingClientProperties, HttpLoggingInterceptor.Level.NONE);

**Comment by NekoSunflower** [comment]
已解决
