### ISSUE TITLE
开发 Bilibili Web API

### ISSUE THREAD

**Issue by czp3009** [czp3009/bilibili-api#5]
已经实现通过 SSO API 获取可用于 Web API 调用的 cookies.

使用得到的 cookies 就可以使用全部的 B站 Web API.

一些内容和功能在 Android APP 上不存在, 例如奖励领取(双端观看直播奖励等), 所以 Web API  可能是必要的.

于是新一波的 API 分析又开始了(躺).

项目文档也不知道该怎么写(扶额).

README 更新了一些编码规范, 诚邀合作开发者.

**Comment by hyhnexus** [comment]
请教您有研究B站的私信API么，实现通过 SSO API 获取可用于 Web API 调用的 cookies后，调用web api的私信接口貌似有限制~

**Comment by czp3009** [comment]
没研究过私信 API, 准确的说, 还没研究过所有 Web API, 不清楚 Web API 是什么情况.

**Comment by SerCom-KC** [comment]
感觉客户端私信用的不是Web API，怀疑是websocket……
至于获取host和port应该是通过 https://api.vc.bilibili.com/link_alloc/v1/alloc/get_list
然而抓包发现貌似是加密的……

**Comment by hyhnexus** [comment]
确实是加密的，感觉只能逆向去分析，如果不是大量发送私信的情况，可以考虑用web api发送私信。
