### ISSUE TITLE
希望添加直播间关于赠送礼物，参与抽奖的API

### ISSUE THREAD

**Issue by yxtj** [czp3009/bilibili-api#9]
如题。

**Comment by czp3009** [comment]
赠送礼物 https://github.com/czp3009/bilibili-api/blob/8005b62bb6f2a8953e8d1cf5a10f70639723fd2d/src/main/java/com/hiczp/bilibili/api/live/LiveService.java#L293

需要先查看自己的背包来知道礼物 id 和礼物在背包中的 id https://github.com/czp3009/bilibili-api/blob/8005b62bb6f2a8953e8d1cf5a10f70639723fd2d/src/main/java/com/hiczp/bilibili/api/live/LiveService.java#L268

抽奖方面, 目前只弄清了小电视抽奖 https://github.com/czp3009/bilibili-api/blob/8005b62bb6f2a8953e8d1cf5a10f70639723fd2d/src/main/java/com/hiczp/bilibili/api/live/LiveService.java#L87

**Comment by yxtj** [comment]
我在LiveService.java的代码里没有找到关于csrf_token和visit_id的字段，我看到网页版新的API已经要求它们了。

**Comment by czp3009** [comment]
csrfToken在对应的页面的HTML中(body中靠前的script标签内)，就是用来防止模拟请求用的。所以Web API可以说是基本报废了

**Comment by czp3009** [comment]
网页API不想搞了，全剧终
